# Generated by Django 4.2.11 on 2026-05-09 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('olts', '0001_initial'),
        ('vlans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('mac_address', models.CharField(blank=True, default='', max_length=17)),
                ('pon_port', models.CharField(blank=True, default='', max_length=50)),
                ('onu_index', models.IntegerField(default=0)),
                ('onu_id', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('unregistered', 'Unregistered'), ('registered', 'Registered'), ('active', 'Active'), ('offline', 'Offline'), ('provisioning', 'Provisioning')], default='unregistered', max_length=20)),
                ('signal_strength', models.FloatField(blank=True, null=True)),
                ('service_profile', models.CharField(blank=True, default='', max_length=100)),
                ('provision_method', models.CharField(choices=[('snmp', 'SNMP'), ('telnet', 'Telnet'), ('hybrid', 'Hybrid'), ('none', 'None')], default='none', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onus', to='olts.olt')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onus', to='vlans.vlan')),
            ],
            options={
                'db_table': 'onus',
                'ordering': ['-created_at'],
                'unique_together': {('olt', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='ProvisioningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_logs', to='onus.onu')),
            ],
            options={
                'db_table': 'provisioning_logs',
                'ordering': ['created_at'],
            },
        ),
    ]
