# Generated by Django 4.2.11 on 2026-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onus', '0002_drop_provision_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onu',
            name='pon_port',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='onu',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='onu',
            name='status',
            field=models.CharField(choices=[('unregistered', 'Unregistered'), ('registered', 'Registered'), ('active', 'Active'), ('offline', 'Offline'), ('provisioning', 'Provisioning')], db_index=True, default='unregistered', max_length=20),
        ),
    ]
