# Generated by Django 4.2.13 on 2026-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onus', '0003_add_db_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='onu',
            index=models.Index(fields=['olt', 'status'], name='onus_olt_status_idx'),
        ),
    ]
