# Generated by Django 4.2.11 on 2026-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlans', '0003_vlan_source_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='source',
            field=models.CharField(choices=[('managed', 'Managed (created in dashboard)'), ('discovered', 'Discovered (read from OLT)')], db_index=True, default='managed', max_length=16),
        ),
    ]
