# Generated by Django 4.2.11 on 2026-05-09 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('snmp_version', models.CharField(choices=[('v1', 'SNMPv1'), ('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], default='v2c', max_length=4)),
                ('snmp_read_community', models.CharField(default='public', max_length=100)),
                ('snmp_write_community', models.CharField(blank=True, default='', max_length=100)),
                ('telnet_enabled', models.BooleanField(default=False)),
                ('telnet_port', models.PositiveIntegerField(default=23)),
                ('telnet_username', models.CharField(blank=True, default='admin', max_length=50)),
                ('telnet_password', models.CharField(blank=True, default='admin', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('configuring', 'Configuring'), ('active', 'Active'), ('error', 'Error'), ('offline', 'Offline')], default='pending', max_length=20)),
                ('system_name', models.CharField(blank=True, default='', max_length=200)),
                ('system_description', models.CharField(blank=True, default='', max_length=500)),
                ('system_uptime', models.CharField(blank=True, default='', max_length=100)),
                ('last_polled', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'olts',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='SetupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_logs', to='olts.olt')),
            ],
            options={
                'db_table': 'setup_logs',
                'ordering': ['created_at'],
            },
        ),
    ]
