# Generated by Django 4.2.11 on 2026-05-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='olt_admin_password',
            field=models.CharField(blank=True, default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='olt',
            name='olt_admin_username',
            field=models.CharField(blank=True, default='admin', max_length=50),
        ),
    ]
