# Generated by Django 4.2.13 on 2026-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olts", "0002_olt_olt_admin_password_olt_olt_admin_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="olt",
            name="snmp_read_community",
            field=models.CharField(default="autoolt_read", max_length=100),
        ),
        migrations.AlterField(
            model_name="olt",
            name="snmp_write_community",
            field=models.CharField(blank=True, default="autoolt_write", max_length=100),
        ),
    ]
