# Generated by Django 4.2.13 on 2026-05-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("olts", "0003_snmp_community_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="OLTPort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("if_index", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "port_type",
                    models.CharField(
                        choices=[
                            ("pon", "PON / GPON"),
                            ("uplink", "Uplink / Ethernet"),
                            ("lag", "LAG / Trunk"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("up", "Up"),
                            ("down", "Down"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("speed_mbps", models.IntegerField(default=0)),
                ("onu_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "olt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="olts.olt",
                    ),
                ),
            ],
            options={
                "db_table": "olt_ports",
                "ordering": ["port_type", "name"],
                "unique_together": {("olt", "if_index")},
            },
        ),
    ]
