# Generated by Django 4.2.11 on 2026-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olts', '0010_drop_telnet_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olt',
            name='olt_admin_password',
            field=models.CharField(blank=True, default='admin', max_length=500),
        ),
    ]
