# Generated by Django 4.2.11 on 2026-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olts', '0011_encrypt_olt_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('configuring', 'Configuring'), ('active', 'Active'), ('error', 'Error'), ('offline', 'Offline')], db_index=True, default='pending', max_length=20),
        ),
    ]
