# Generated by Django 4.2.13 on 2026-05-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olts', '0012_add_db_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olt',
            name='last_polled',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
