# Generated by Django 4.2.11 on 2026-05-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olts', '0018_mikrotik_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
